language: go
go:
  - 1.14.x
services:
  - xvfb
addons:
  homebrew:
    update: true
    packages:
      - go@1.14
      - make
      - coreutils
      - findutils
      - gnu-tar
      - gnu-sed
      - gawk
      - gnutls
      - gnu-indent
      - gnu-getopt
      - grep
  apt:
    packages:
      - gcc
      - libc6-dev
      - libx11-dev
      - xorg-dev
      - libxtst-dev
      - gcc-multilib
      - gcc-mingw-w64
os:
  - linux
  - osx
install:
  - GO111MODULE=on go get
script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then export PATH="$(brew --prefix)/opt/make/libexec/gnubin:${PATH}" ; fi
  - make tools
  - make lint
  - make test
  - make coverage
  - make BUILDNAME=${TRAVIS_OS_NAME} build
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then CC=x86_64-w64-mingw32-gcc GOOS=windows CGO_ENABLED=1 go build -o .build/windows.exe main.go ; fi
deploy:
  provider: releases
  api_key:
    secure: n2pSGM0ygiIptoWD/D9W0VokURsI8p44+qFsBbMuWz1kG3agzsHfJR8ufvYVYnl3CelupOHoU11+uM/R3am5djnqVkpYZhdvJznEaLzdPZeLDuMaMF0GLm6o5UFpcA0nf/68RAaLaBg4iXCBrSfN5nnrscxdmKOfQ1V8PwhkIZNkKXaXBK2myx9o6uhSfuRYHvXlTtZ01R8Yy7l/3TB6I841OuGMsxI/klDPFF/6DYe0bbgmh6Q6FRAsGAZGfrWGUGa4g5gi9cBpYGyR0vZfMxy4nlSaF2Owi9Pguj/8gWabmHLDSyWZqDOcrp2VlVALMNTMeP+0s2MNkp9CbFjlngMoykh1cV/wC/OGKyWasqKLAgX+HTDhGjDIsbhEyaK9RydKUSW4CNAoOJU3jzONOrCocFsmuGRP7H9XoS2XDK7X4cbCJEIbkgqQqSPRKz+i4fdPE5eUiSlxvy4QDE24YUrcIdpyND0naF1OMqyqkMqXVHf2cmqqMWYSoz3FRy4uLs81Mq2hFcQBjYKoSSrJ5UfKrtU5PZy7UpGDPRvCzVaiXpRrCZgRVhuDAAZPa3CvJmN5xDYUTjRc42fziIAwwbtAB0uq40O3xdIYGxt1GaUnagaucbU1aBbc3T/X/o/yDdUA/os6hXSh6FtKdIm/qGD+jssvHi44ILDYdaeTmuw=
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/.build/*
  on:
    repo: kevinconway/remouseable
    tags: true
  skip_cleanup: true
  cleanup: false
