language: go
go:
  - "1.13.x"
services:
  - xvfb
addons:
  homebrew:
    packages:
    - go@1.13
    - make
  apt:
    packages:
    - gcc
    - libc6-dev
    - libx11-dev
    - xorg-dev
    - libxtst-dev
    - libpng++-dev
    - xcb
    - libxcb-xkb-dev
    - x11-xkb-utils
    - libx11-xcb-dev
    - libxkbcommon-x11-dev
    - libxkbcommon-dev
    - xsel
    - xclip
os:
  - linux
  - osx
install:
  - GO111MODULE=on go get
script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then export PATH="$(brew --prefix)/opt/make/libexec/gnubin:${PATH}" ; fi
  - make tools
  - make lint
  - make test
  - make coverage
  - make BUILDNAME=${TRAVIS_OS_NAME} build
deploy:
  provider: releases
  api_key:
    secure: "AkKGnjv8F84wq+B4TJiyvYLZzTwBCoSW9eLzSbtxFjxgJntfvg+Au7WvvOma1gaVKd35IKWGITLZ9D3K9n3cCcUbobaz31IsoFtpXSzS9atspx5dR8CPuntSrYB4NT6xBrLtV82tOvRrVfKW6LQPOEKOZwilEGRQ1vYy4GxqjfgiorFS9Hm5cif4iL2v/hkMKnVJvyXyEJAR0DAzs8WW0kvDF9niQr+0ReOIT9OpaywG8YmS8T1krdgtYaGlujBJF13/BIpYDxJzczfzPStnDUhAe3k/DfUxSjYn/yJxG/AzC3JYm7MaKKentz0Zrd1NuzS5AzaGqMgCREfHHiZoPSdX2C7dJ0zmMmSpOXiR5csFgkGs3Zq0wT4mQ3qfzo1CUmy3sRVqjL7lPvN0o8NQTnLka3/iGaJVGw5zip5Nv0O+551ReD1O5RubzovJVCkZclJwaMr/VxWnfoRuIt93hmsaoEu1x9/LznPNYJvXcUtLgmyM0RnUzJdQTOR3C0e5UAppoL+76sZqtnCwUOgv7j68bxlFbvAahem4v5Rpth72F4tIgkm8eJlVEmFtlf6/Ubpxi1D8rSTo9+wFfBkTr8b5XMtE7kJoUjneB+3d0PpOX1n59mcR2np7mgq9v0B1GYxRvjF9cFHKrFQCKpoNS4TgjiKSZ860MLpbUZNrY1g="
  file: ${TRAVIS_OS_NAME}
  cleanup: false
  on:
    tags: true
